### ISSUE TITLE
Can connect more than one device to a WDS Sink

### ISSUE THREAD

**Issue by fmoyaarnao** [01org/wds#115]
Morning,

I would like to connect more than one device to a WDS sink.

Now for each "P2P :: Peer", "connman" starts a new DHCP server with a new IP domain.
So, exists any way to connect more than one device to the WDS Sink? Configuring "connman" in a specific mode, change the way to create the WDS Sink, ...

Thank you.

Francisco Moya

**Comment by kanavin** [comment]
Sources and sinks connect via private p2p wi-fi networks, so mutliple dhcp servers will not clash with each other. Having several sources connected at the same time to the same sink should not be a problem, although I can't think of a scenario where that would be useful.

**Comment by jku** [comment]
> ... Configuring "connman" in a specific mode ...

Last I looked connman/wpa_supplicant did not support multiple peers, even if the P2P spec allows that.
