### ISSUE TITLE
Missed step to setup

### ISSUE THREAD

**Issue by albfan** [01org/wds#122]
I miss an step from WDS sink test

    connmanctl> peers
    <my device> idle peer_<mac>_<mac>
    ...
    connmanctl> connect peer_<mac>_<mac>

Afer that laptop works smoothly as a sink

**Comment by jku** [comment]
manually connecting (using connman) should not be required. If things don't work without doing that, there's probably a bug somewhere -- wds, connman or wpa_supplicant.

**Comment by albfan** [comment]
Ok thanks, I will double check
