### ISSUE TITLE
incorrect switch use

### ISSUE THREAD

**Issue by setharnold** [01org/wds#166]
https://github.com/01org/wds/blob/master/desktop_source/mirac_broker_source.cpp#L45

Note that C++ falls through cases in a switch statement; use of 'break' is mandatory to avoid executing further cases.

```
void MiracBrokerSource::on_connection_failure(ConnectionFailure failure) {
  switch (failure) {
      case CONNECTION_LOST:
          std::cout << "* RTSP connection lost" << std::endl;
      case CONNECTION_TIMEOUT:
          std::cout << "* RTSP connection failed: timeout" << std::endl;
  }
}
```

If `failure == CONNECTION_LOST` then two error messages will be printed.

Thanks

**Comment by jku** [comment]
You'd think 20 years of coding in C would mean this doesn't happen... but no. I don't currently even have this repo cloned so would appreciate if anyone else could fix my mistake here.

**Comment by setharnold** [comment]
Thanks alexshalamov, nice.

jku, it could be worse :) http://users.csc.calpoly.edu/~jdalbey/SWE/Papers/att_collapse.html

Thanks
